In [1]:
import pandas as pd
import os
import glob

In [2]:
path = os.getcwd()
csv_files = glob.glob(os.path.join(path, "*.csv"))

In [3]:
for f in csv_files:
      
    # read the csv file
    df = pd.read_csv(f)
      
    # print the location and filename
    print('Location:', f)
    print('File Name:', f.split("\\")[-1])
      
    # print the content
    print('Content:')
    display(df)
    print()

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_1967.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_1967.csv
Content:

   Unnamed: 0      amplitude       phase  amplitude (m)
0          Z0      11.742087    0.000000       0.011742
1          M2     173.701000  281.885871       0.173701
2          S2  105697.361006   49.294858     105.697361
3          N2     334.561930  219.751878       0.334562
4          K1    1312.153074  170.144997       1.312153
5          M4       0.984234  143.703102       0.000984
6          O1      15.922652  211.082064       0.015923
7          M6       1.100034  157.365749       0.001100
8         MK3       8.226478    9.439683       0.008226
9          S4       5.983009  142.720114       0.005983
10        MN4       3.676890   55.258119       0.003677
11        nu2     369.933196   37.481401       0.369933
12         S6       1.760073  337.078542       0.001760
13        mu2     142.693757  307.959908       0.142694
14        2N2     100.867394  133.211005       0.100867
15        OO1       2.086799  105.522299       0.002087
16    lambda2    2279.996144  348.113017       2.279996
17         S1    2815.601961   77.147326       2.815602
18         M1      17.444244  283.055190       0.017444
19         J1      11.184977  101.520328       0.011185
20        MSF     134.907511   57.762698       0.134908
21         Mf     105.796665  249.920892       0.105797
22       rho1      40.852077  216.393832       0.040852
23         Q1      51.514853   46.196073       0.051515
24         T2   43353.709427  144.569151      43.353709
25         R2   87517.546129  133.697237      87.517546
26        2Q1       3.980858   44.855921       0.003981
27         P1    1426.623029  338.635919       1.426623
28       2SM2      14.833636  256.525078       0.014834
29         M3       6.870442   19.808564       0.006870
30         L2    4410.259905  158.620055       4.410260
31       2MK3       7.738971  211.230915       0.007739
32         K2   19603.333004   52.012556      19.603333
33         M8       2.094388  256.776546       0.002094
34        MS4       7.823079   27.923710       0.007823

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_1970.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_1970.csv
Content:

   Unnamed: 0    amplitude       phase  amplitude (m)
0          Z0    36.615960    0.000000       0.036616
1          M2    34.633515   12.789199       0.034634
2          S2   348.130885  132.062508       0.348131
3          N2   163.679268  280.784892       0.163679
4          K1  1038.990962  297.534775       1.038991
5          M4     6.002683  172.757526       0.006003
6          O1     7.527859  324.114893       0.007528
7          M6     0.618045  111.785408       0.000618
8         MK3     2.876814   36.947088       0.002877
9          S4     5.099696  282.444819       0.005100
10        MN4     4.408880   96.393001       0.004409
11        nu2   158.718857  205.171658       0.158719
12         S6     2.872345  100.601021       0.002872
13        mu2    99.356829  137.589077       0.099357
14        2N2    87.051374  215.087063       0.087051
15        OO1     9.931860   49.405468       0.009932
16    lambda2   304.397105  338.677437       0.304397
17         S1  2406.595980  355.001476       2.406596
18         M1    10.611762  209.149784       0.010612
19         J1    18.411131  145.462436       0.018411
20        MSF   125.489845  342.809147       0.125490
21         Mf    80.570412  243.408797       0.080570
22       rho1   100.659465  158.685293       0.100659
23         Q1    91.581892  242.695773       0.091582
24         T2   552.388442  336.128835       0.552388
25         R2   929.556894  155.500750       0.929557
26        2Q1    10.721130  269.327655       0.010721
27         P1  1273.613481   56.550881       1.273613
28       2SM2    13.712520  333.769667       0.013713
29         M3     7.676040  113.954962       0.007676
30         L2   427.881403  281.587013       0.427881
31       2MK3     5.046653  248.365084       0.005047
32         K2   438.991740  303.519425       0.438992
33         M8     2.142347   42.176311       0.002142
34        MS4     2.652210   11.654102       0.002652

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_1971.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_1971.csv
Content:

   Unnamed: 0    amplitude       phase  amplitude (m)
0          Z0    35.301041    0.000000       0.035301
1          M2    71.288848   96.734168       0.071289
2          S2   278.778780  352.825075       0.278779
3          N2   321.325370  105.375563       0.321325
4          K1  2190.074145   53.841817       2.190074
5          M4     4.389258  322.547364       0.004389
6          O1    37.153800  194.812149       0.037154
7          M6     2.127533  209.394174       0.002128
8         MK3     5.370311  197.290832       0.005370
9          S4    13.581351  114.863792       0.013581
10        MN4    13.068747  130.014624       0.013069
11        nu2   315.862931   66.656719       0.315863
12         S6     4.689929  297.984140       0.004690
13        mu2   153.703878   80.338800       0.153704
14        2N2   105.235361  112.768432       0.105235
15        OO1     7.948572  304.694760       0.007949
16    lambda2   482.861904  303.662782       0.482862
17         S1  4655.712850   45.431073       4.655713
18         M1    24.627674  105.095995       0.024628
19         J1    17.687351  219.165813       0.017687
20        MSF   129.963435  284.720156       0.129963
21         Mf    93.076332  332.857681       0.093076
22       rho1   130.492927  151.947792       0.130493
23         Q1   104.300447  186.952554       0.104300
24         T2   931.965870  152.331383       0.931966
25         R2  1618.790654  130.015763       1.618791
26        2Q1    23.612402   19.810900       0.023612
27         P1  2353.700047   43.503843       2.353700
28       2SM2     5.041914  325.351302       0.005042
29         M3     2.551670  212.530028       0.002552
30         L2   582.739973  249.665550       0.582740
31       2MK3     6.257251  161.881829       0.006257
32         K2   845.661216  344.248247       0.845661
33         M8     3.220993   68.231315       0.003221
34        MS4     2.947954  182.465434       0.002948

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_1965.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_1965.csv
Content:

   Unnamed: 0    amplitude       phase  amplitude (m)
0          Z0    96.278465    0.000000       0.096278
1          M2   132.213629  341.114574       0.132214
2          S2  1664.026702  310.667683       1.664027
3          N2   398.309667  113.432231       0.398310
4          K1  1004.361142  305.939633       1.004361
5          M4     4.676605  184.438342       0.004677
6          O1    11.576767  321.861878       0.011577
7          M6     0.787978  145.996365       0.000788
8         MK3     9.732994  105.321006       0.009733
9          S4     6.340746  151.243096       0.006341
10        MN4     2.864133   28.605056       0.002864
11        nu2   384.070295   66.941871       0.384070
12         S6     3.223685    5.303169       0.003224
13        mu2   224.294210  190.654478       0.224294
14        2N2   183.814362  233.239923       0.183814
15        OO1     8.608851  308.084228       0.008609
16    lambda2   949.750087   83.092294       0.949750
17         S1  2240.766477   26.629729       2.240766
18         M1    17.636663  285.617862       0.017637
19         J1     8.765720  299.391832       0.008766
20        MSF    74.026888   55.220898       0.074027
21         Mf    78.426524  251.350145       0.078427
22       rho1    36.599089  146.631162       0.036599
23         Q1    35.495926  181.345385       0.035496
24         T2  2772.807719  214.603181       2.772808
25         R2  3278.340810   42.935023       3.278341
26        2Q1    21.072006  285.132578       0.021072
27         P1  1205.990911   99.902275       1.205991
28       2SM2     6.320932   88.588786       0.006321
29         M3    10.712941  212.197054       0.010713
30         L2   909.888662   50.374085       0.909889
31       2MK3     7.675411  331.285717       0.007675
32         K2  2118.460120  146.919828       2.118460
33         M8     1.196601  218.376341       0.001197
34        MS4     3.965451   73.501270       0.003965

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2014.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2014.csv
Content:

   Unnamed: 0    amplitude       phase  amplitude (m)
0          Z0    92.058050  180.000000       0.092058
1          M2    98.825662  118.139896       0.098826
2          S2  1122.977402  218.851550       1.122977
3          N2   361.330347   16.111547       0.361330
4          K1  1154.176345  167.403966       1.154176
5          M4     4.241935  263.972244       0.004242
6          O1     0.347555  262.088959       0.000348
7          M6     3.341684   10.148947       0.003342
8         MK3     7.466370  114.876907       0.007466
9          S4     5.567264   92.553000       0.005567
10        MN4    12.154593  272.193530       0.012155
11        nu2   372.009503  305.330162       0.372010
12         S6     3.360042  165.145730       0.003360
13        mu2   210.587417  220.130168       0.210587
14        2N2   185.513949  289.388032       0.185514
15        OO1    20.055471  339.275444       0.020055
16    lambda2   557.995449   95.710858       0.557995
17         S1  2056.039251  237.353030       2.056039
18         M1    16.575467  110.567968       0.016575
19         J1    33.751238  102.098211       0.033751
20        MSF    88.988025  154.604513       0.088988
21         Mf   154.283654   41.620078       0.154284
22       rho1    79.359589  107.885230       0.079360
23         Q1    70.960397  167.013787       0.070960
24         T2  1393.872087  111.159333       1.393872
25         R2  1187.116445  302.262548       1.187116
26        2Q1    24.853291  181.449258       0.024853
27         P1  1067.858380  309.698578       1.067858
28       2SM2    18.315022  203.188788       0.018315
29         M3     4.933670  116.312365       0.004934
30         L2   660.242671   36.456488       0.660243
31       2MK3    16.048904  242.369956       0.016049
32         K2  1333.857700   82.187019       1.333858
33         M8     0.704546   24.885742       0.000705
34        MS4     3.965236  230.558570       0.003965

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2015.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2015.csv
Content:

   Unnamed: 0    amplitude       phase  amplitude (m)
0          Z0    57.749980  180.000000       0.057750
1          M2    45.356534  330.270085       0.045357
2          S2   561.379286  326.127428       0.561379
3          N2    73.234758  334.494341       0.073235
4          K1  1904.052196  288.761319       1.904052
5          M4     1.156021  123.747905       0.001156
6          O1    31.872337   89.138665       0.031872
7          M6     1.459328  346.725954       0.001459
8         MK3    12.989204  342.567778       0.012989
9          S4     1.588886  264.777383       0.001589
10        MN4     5.359639  288.580861       0.005360
11        nu2    90.943936  213.321203       0.090944
12         S6     3.045915  308.570949       0.003046
13        mu2    70.745285  262.555178       0.070745
14        2N2    64.683334   32.366159       0.064683
15        OO1    13.394119   87.259730       0.013394
16    lambda2   447.652867  325.430801       0.447653
17         S1  3424.442859  342.598620       3.424443
18         M1    24.585539  233.528964       0.024586
19         J1    32.325187  169.016930       0.032325
20        MSF   104.114109  292.564092       0.104114
21         Mf   130.858066  191.265418       0.130858
22       rho1   141.473019  271.390965       0.141473
23         Q1   168.336922   28.564579       0.168337
24         T2  1248.459240  238.716631       1.248459
25         R2  1913.590735  113.485045       1.913591
26        2Q1    21.528477  271.406203       0.021528
27         P1  1789.206269   36.136877       1.789206
28       2SM2    23.929140   60.158500       0.023929
29         M3     9.570010  143.176228       0.009570
30         L2   593.128327  200.126440       0.593128
31       2MK3     2.176568  246.393340       0.002177
32         K2  1696.878680  246.030976       1.696879
33         M8     1.170330   18.942411       0.001170
34        MS4     9.302621    9.287529       0.009303

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2001.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2001.csv
Content:

   Unnamed: 0    amplitude       phase  amplitude (m)
0          Z0     3.992418  180.000000       0.003992
1          M2    71.763212  274.545851       0.071763
2          S2   487.022613  129.496728       0.487023
3          N2   256.061512  148.625186       0.256062
4          K1  2725.906120  114.306720       2.725906
5          M4     8.495680  177.169350       0.008496
6          O1    20.233901  100.177726       0.020234
7          M6     2.249377  320.914600       0.002249
8         MK3     1.754340  324.984967       0.001754
9          S4     4.774231  312.011963       0.004774
10        MN4    11.235605   42.904197       0.011236
11        nu2   238.297718   74.520363       0.238298
12         S6     1.238451  108.370852       0.001238
13        mu2   141.939344  312.905195       0.141939
14        2N2   123.999891   27.739691       0.124000
15        OO1    34.484185  303.093187       0.034484
16    lambda2   295.044484  304.393399       0.295044
17         S1  5731.680022  181.188174       5.731680
18         M1    41.556680  165.106090       0.041557
19         J1    44.938894   14.879930       0.044939
20        MSF    41.824354   65.899405       0.041824
21         Mf    51.476976  287.277280       0.051477
22       rho1   115.398984  261.790968       0.115399
23         Q1   102.461288  334.847926       0.102461
24         T2   629.214819  357.647387       0.629215
25         R2   717.723199  196.438881       0.717723
26        2Q1    36.744751   44.483954       0.036745
27         P1  3012.789584  239.917652       3.012790
28       2SM2     8.479814  309.305226       0.008480
29         M3    10.760395  254.965494       0.010760
30         L2   336.245385  251.823201       0.336245
31       2MK3     9.930834  130.681201       0.009931
32         K2   549.485332  326.932844       0.549485
33         M8     2.066114  311.730976       0.002066
34        MS4     4.154956   76.602937       0.004155

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2017.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2017.csv
Content:

   Unnamed: 0    amplitude       phase  amplitude (m)
0          Z0    30.282225  180.000000       0.030282
1          M2    24.542781  356.991538       0.024543
2          S2  1464.882260  134.007628       1.464882
3          N2   134.780779  212.468732       0.134781
4          K1   390.429348   40.318259       0.390429
5          M4     6.291916  344.416961       0.006292
6          O1     7.383403  104.923620       0.007383
7          M6     2.046267   63.610347       0.002046
8         MK3    12.283077  296.920159       0.012283
9          S4     1.683980  130.891187       0.001684
10        MN4    11.171474  177.162770       0.011171
11        nu2   132.430160  286.295666       0.132430
12         S6     3.599913  241.319024       0.003600
13        mu2   125.586025  104.573689       0.125586
14        2N2   114.542841   30.916022       0.114543
15        OO1    30.142666  272.808516       0.030143
16    lambda2   444.501078  310.491597       0.444501
17         S1   784.701115  107.283327       0.784701
18         M1    16.255290  147.642389       0.016255
19         J1    16.751654   97.138218       0.016752
20        MSF    86.347273  317.009967       0.086347
21         Mf   103.439941  211.869012       0.103440
22       rho1    43.404090  289.635714       0.043404
23         Q1    67.266089  217.599599       0.067266
24         T2  1795.326138   37.916682       1.795326
25         R2  1763.396351  282.249734       1.763396
26        2Q1    16.817936   92.201926       0.016818
27         P1   455.702561  167.393768       0.455703
28       2SM2    12.281282   33.362932       0.012281
29         M3    14.298865  265.049600       0.014299
30         L2   454.826825   21.420502       0.454827
31       2MK3    17.578953  356.703406       0.017579
32         K2  1740.912155   38.127895       1.740912
33         M8     1.530818   96.456123       0.001531
34        MS4     9.285577  345.382181       0.009286

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2016.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2016.csv
Content:

   Unnamed: 0    amplitude       phase  amplitude (m)
0          Z0    55.948702  180.000000       0.055949
1          M2    26.815913   84.781661       0.026816
2          S2   302.167978  192.922319       0.302168
3          N2    88.111762  321.479647       0.088112
4          K1  1248.104258   47.943575       1.248104
5          M4     4.449147   96.562412       0.004449
6          O1    19.810968  125.791934       0.019811
7          M6     2.059328  305.442997       0.002059
8         MK3     3.716357   60.726369       0.003716
9          S4     4.944898   39.697357       0.004945
10        MN4     7.029655   46.936463       0.007030
11        nu2    83.925839  111.484795       0.083926
12         S6     3.993737  350.975572       0.003994
13        mu2    75.061681    7.953089       0.075062
14        2N2    54.660637  216.615676       0.054661
15        OO1    22.007138   40.345309       0.022007
16    lambda2    62.953497  227.725144       0.062953
17         S1  2199.463569  103.819785       2.199464
18         M1    32.001563  242.992243       0.032002
19         J1    12.582730   49.442432       0.012583
20        MSF    56.780665  145.494590       0.056781
21         Mf    42.159093   34.467725       0.042159
22       rho1    89.680765  308.904181       0.089681
23         Q1    92.323354  137.179406       0.092323
24         T2   376.351326   67.099075       0.376351
25         R2   589.503342  282.592168       0.589503
26        2Q1    11.085514  257.866227       0.011086
27         P1  1114.410603  156.718797       1.114411
28       2SM2     8.974008   37.354568       0.008974
29         M3     4.051556   97.450112       0.004052
30         L2    58.666567   22.470625       0.058667
31       2MK3    11.696991   43.322686       0.011697
32         K2   686.584020   61.267493       0.686584
33         M8     1.863318  189.960181       0.001863
34        MS4     1.342283  215.292507       0.001342

Location: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2010.csv
File Name: /Users/dilemmajayne/Dropbox/NunatsiavutFutures/CoastalErosion_WebbsBay/Tides/Decomposition_results/ComponentsAmplitude_2010.csv
Content:

   Unnamed: 0    amplitude       phase  amplitude (m)
0          Z0    25.996642  180.000000       0.025997
1          M2    56.872333  242.311053       0.056872
2          S2   239.237597    0.351854       0.239238
3          N2   226.356932  282.206000       0.226357
4          K1   976.784764  172.993682       0.976785
5          M4     7.420953  284.914884       0.007421
6          O1     5.689531  138.245129       0.005690
7          M6     1.986017  130.209887       0.001986
8         MK3    11.848463  117.871252       0.011848
9          S4     2.078814  141.858819       0.002079
10        MN4     9.742244   80.744680       0.009742
11        nu2   227.966410  205.472878       0.227966
12         S6     4.710137   46.414147       0.004710
13        mu2   146.917368  252.654974       0.146917
14        2N2   130.022420  323.345848       0.130022
15        OO1     8.740089  232.606715       0.008740
16    lambda2   331.297885   57.378810       0.331298
17         S1  1990.872208  213.307252       1.990872
18         M1    13.154632  353.740399       0.013155
19         J1     2.361262  162.304032       0.002361
20        MSF    79.490185   67.719280       0.079490
21         Mf    51.517281    6.546794       0.051517
22       rho1    87.172233   83.225309       0.087172
23         Q1    83.249858  149.166294       0.083250
24         T2   446.845598  247.517353       0.446846
25         R2   388.744588  123.218120       0.388745
26        2Q1    21.387554   17.900104       0.021388
27         P1  1005.684939  262.643573       1.005685
28       2SM2    12.348471   83.209896       0.012348
29         M3     4.050933  205.730374       0.004051
30         L2   496.208255  347.904557       0.496208
31       2MK3     1.934749  220.883852       0.001935
32         K2   224.308299  284.074984       0.224308
33         M8     0.245243  323.831601       0.000245
34        MS4     4.722646  258.058631       0.004723